### ISSUE TITLE
Background -color

### ISSUE THREAD

**Issue by KSnehal11** [calcont/whiteboard#6]
when i select bg color - black or any dark color then cursor and the shape which i have drawn can't be seen , so i suggest that when bg color get dark that time cursor and the things which are already drawn should get white color

**Comment by Amark19** [comment]
Hey @KSnehal11 the concern u have raised will be solve in next version where will be adding a option to edit all objects including borders,colors,width,height etc.
That's why closing this ticket.
Thanks !
